version: '1.0'
enabled: {}
defaults: {}
annotations:
  POST:/api/v1/auth/login:
    x-uigen-login: true
  POST:/api/v1/auth/password-reset:
    x-uigen-password-reset: true
  POST:/api/v1/auth/sign-up:
    x-uigen-signup: true
relationships:
  - source: templates
    target: meetings
    path: /api/v1/meetings/{meeting_id}/templates/{template_id}
    type: hasMany
  - source: meetings
    target: generate-documents
    path: /api/v1/meetings/{meeting_id}/generate-documents
    type: hasMany
