version: '1.0'
enabled: {}
defaults: {}
annotations:
  POST:/api/v1/auth/login:
    x-uigen-login: true
    x-uigen-label: User Login
  POST:/api/v1/auth/password-reset:
    x-uigen-password-reset: true
  POST:/api/v1/auth/sign-up:
    x-uigen-signup: true
  GET:/health:
    x-uigen-ignore: true
  Body_create_meeting_api_v1_meetings_post.recording:
    x-uigen-max-file-size: 62914560
  Body_upload_template_api_v1_templates_post.file:
    x-uigen-max-file-size: 62914560
relationships: []
canvasLayout:
  positions:
    me:
      x: 412
      'y': 441
    confirm:
      x: 0
      'y': 160
    password-reset:
      x: 81
      'y': 415
    sign-up:
      x: 913
      'y': 300
    login:
      x: 669
      'y': 357
    meetings:
      x: 372
      'y': 63
    templates:
      x: 773
      'y': 794
